theme: jekyll-theme-minimal
title: Theodora Kontogianni

avatar: theodora_kontogianni_image.jpg

# Author Settings
author: Theodora Kontogianni # add your name
author-img: theodora_kontogianni_image.jpg # add your photo
